Logger
ISSUIUC/ISS_SILSIM pull request #14
Opened 2021-12-24 06:21 UTC by mjacob1002

Integrated spdlog, and added how to log in the SIM_DEBUG section of Simulation.cpp. Also created log dir where the log files will be stored.

2021-12-24 08:03 UTC, AyberkY requested changes
Hey Matthew, spdlog looks pretty 🔥 for how lightweight it is.

Are you on the ISS slack currently? We'd love to have you join us so you can continue contributing to SILSIM. Let me know if you're interested and I can add you so you can stay up to date on meetings and such.

Regarding logging in SILSIM, using spdlog as a backend logging engine seems like a good idea. However I do think the logging system in SILSIM can be taken much much further. I'm suggesting implementing a mechanism that'll allow any object in SILSIM to log relevant data. I was also thinking of writing some Python to then parse these logs and make the data available in dictionaries convenient for analysis. I'd love to talk about where this could go and collaborate.

For this particular PR:
 - We're trying to move towards using project/milestone tickets in Trello. Since adding logging is a somewhat large project, I'm going to make [AV-44] a project ticket.

 - I've made [AV-268] as the ticket for importing or implementing a logging library. The work in this branch should be associated with this ticket going forward. Since you have a PR open, I've move it to "In Review" 

 - Please try to follow the branch naming convention in the SILSIM readme. I'd suggest something along the lines of `feature/AV-268-import-spdlog-logging-library`

 - I'd also suggest renaming the PR name to include the ticket ID. Something like `[AV-268] Import spdlog Logging Library`

2021-12-25 02:04 UTC, NPIPHI requested changes
A few things:
- You forgot to commit the .gitmodules file, so spdlog won't download automatically
- theres more printfs in physicsengine.cpp
- you committed the logs

2021-12-29 04:30 UTC, NPIPHI approved these changes

2021-12-29 04:32 UTC, NPIPHI approved these changes
LGTM

2021-12-29 04:42 UTC, merged