rmoved outparam getters, fixed sensor bug
ISSUIUC/ISS_SILSIM pull request #24
Opened 2022-01-26 17:43 UTC by NPIPHI

Outparam getters are less clear and readable than return by value getters. Also fixed bug in sensors that assumed a function used an out parameter when it didn't.

2022-01-27 20:45 UTC, AyberkY requested changes
The change in `Accelerometer::get_data()` forgets to assign the acceleration vector to the class member `data_`.

I fixed that and ran the sim again, but I still see weird behavior in the sensor plot:
![image](https://user-images.githubusercontent.com/35669067/151440675-52ba1706-d9b0-4f2c-b842-07e3a1fd1364.png)

^ Not sure what's going on here

2022-01-27 20:45 UTC, AyberkY commented on includes/Rocket.h
>      /************* Set parameters (all passed by reference) ***************/
"all passed by reference" no longer accurate

2022-01-27 20:45 UTC, AyberkY commented on src/Sensor.cpp
> +        rocket_.i2r(rocket_.get_r_ddot());
Forgot to assign this to `data_`

2022-01-28 17:35 UTC, NPIPHI commented
The plots look like that because Accelerometer logs data in rocket reference frame while the true values are logged in inertial reference frame.

2022-01-28 17:38 UTC, NPIPHI commented
Accelerometer also shouldn't feel acceleration from gravity when its flying but that's a different issue

2022-02-09 18:39 UTC, merged