AV 273 Geodesic Earth
ISSUIUC/ISS_SILSIM pull request #28
Opened 2022-02-08 00:03 UTC by JacobGugala

New functions that convert the existing inertial frame position to Earth-Centered-Earth-Fixed and Geodetic reference frames.
Physics engine now passes geodetic altitude to the atmosphere class.
 [Math](https://en.wikipedia.org/wiki/Geographic_coordinate_conversion)
[Trello](https://trello.com/c/TfpEDcMC/273-av-273-add-geodesic-earth-reference-frame-to-physics-engine)

2022-02-08 00:17 UTC, gautamdayal commented
Tried the plotter and it doesn't go to 80k feet so looks like it works! Can you add comments to outline what the math does because I have absolutely no idea at the moment. Other than that lgtm

2022-02-08 04:26 UTC, AyberkY reviewed
So this isn't a full review yet. I need to look deeper into this and double check your math.

Here's a few things in the meantime:
- Please write doxygen style docstrings for your function implementations. Definitely _do not_ skimp on verbosity on such critical functions like `i2ecef()` and `ecef2geod()`. Provide links to the source of the math, and any explanations that would make it easier to interpret your implementation. See [this function I wrote for [AV-293]](https://github.com/ISSUIUC/ISS_SILSIM/blob/AV-293-implement-physics-using-rasaero-coefficients/src/RASAeroImport.cpp#L136-L172) as an example.
- You should link this PR on the Trello ticket
- #24 is getting rid of outparam getters (i.e. the getters that take in references). I'd suggest merging this branch into yours to get these updates and working from there.
- I'm beginning to think our notation of calling the launchpad's reference frame the "inertial frame" can be a little vague. A more descriptive name like "launchpad_enu_frame" would leave no room for misinterpretation. I feel like that's more favorable over clean function names. 🤔  

Anyway, more to come as I dig deeper, but great work! 🍰

2022-02-10 22:27 UTC, NPIPHI reviewed
Math looks correct, I'll have to take a closer look at it when I'm not in physics discussion lol

2022-02-10 22:27 UTC, NPIPHI commented on includes/PhysicsEngine.h
> +#define _USE_MATH_DEFINES
what's the purpose of the _USE_MATH_DEFINES macro?

2022-02-10 22:27 UTC, NPIPHI commented on src/PhysicsEngine.cpp
> +    rocket_.set_r_geod(ecef2geod(ecef));
you can't call these setters with an r-value, changing the set_r_...(Vector3d & vect) functions to set_r_...(Vector3d vect) will fix this

2022-02-10 22:27 UTC, NPIPHI commented on src/PhysicsEngine.cpp
> +    Vector3d ecef = rocket_.get_r_ecef();
geod and ecef are not really used. ecef is just used to set ecef at the end of the function and geod is never used

2022-02-10 22:27 UTC, NPIPHI commented on src/PhysicsEngine.cpp
> +Vector3d RungeKutta::i2ecef(Vector3d pos_if) {
the unit conversion functions should be part of rocket imo. Since they depend on the launch pad information that is stored in rocket.

2022-02-10 22:27 UTC, NPIPHI commented on includes/Rocket.h
> +    Vector3d r_ecef_{150992.99, -4882549.85, 4087626.55};
why does rocket store its current location in geodesic coordinates and ecef coordinates. It should only store 1 of them and then derive the other from the conversion functions.

2022-02-21 22:58 UTC, NPIPHI requested changes
Gravity should be calculated in geodesic frame

2022-02-21 22:58 UTC, NPIPHI commented on src/PhysicsEngine.cpp
> +    net_force_enu.z() -= (9.81 * mass);
Gravitational acceleration should be in geodesic coordinates

2022-02-22 17:03 UTC, NPIPHI commented
Gravity fix looks good

2022-02-22 19:44 UTC, NPIPHI requested changes
Small bug with atmosphere calculations. The approach of having separate variables for geod coordinates and enu coordinates in rocket is definitely wrong. I think we should store enu coordinates and then always calculate geodesic coordinates from the enu coordinates in the get_r_geod function.

2022-02-22 19:44 UTC, NPIPHI commented on includes/Rocket.h
> +    Vector3d get_r_geod() const { return r_geod_; };
We shouldn't have two separate variables holding coordinates that should always be equal. This function should use the coordinate transformation functions to get the geod coordinates from r_vect

2022-02-22 19:44 UTC, NPIPHI commented on includes/Rocket.h
> +    void set_r_geod(Vector3d vector) { r_geod_ = vector; };
Once r_geod_ is removed this function is unnecessary

2022-02-22 19:44 UTC, NPIPHI commented on includes/Rocket.h
> +    Vector3d r_geod_{40.111801, -88.228691,
Always compute this value from r_vect instead of holding a separate variable

2022-02-22 19:44 UTC, NPIPHI commented on src/PhysicsEngine.cpp
> +#include <iostream>
We don't need iostream

2022-02-22 19:44 UTC, NPIPHI commented on src/PhysicsEngine.cpp
> +        double f_N_mag = c_N * 0.5 * Atmosphere::get_density(r_vect_enu.z()) *
This should be geodesic altitude instead of enu altitude

2022-02-22 19:44 UTC, NPIPHI commented on src/PhysicsEngine.cpp
> +        double f_D_mag = c_D * 0.5 * Atmosphere::get_density(r_vect_enu.z()) *
This should be geodesic altitude instead of enu altitude

2022-02-27 19:24 UTC, NPIPHI approved these changes

2022-02-27 19:25 UTC, merged